# Generated by Django 2.2.4 on 2019-08-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190826_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.FileField(default=False, upload_to='static'),
        ),
    ]
